FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY SmartCity.API/SmartCity.API.csproj SmartCity.API/
RUN dotnet restore "SmartCity.API/SmartCity.API.csproj"

COPY SmartCity.API/ SmartCity.API/
WORKDIR /src/SmartCity.API
RUN dotnet publish "SmartCity.API.csproj" -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:10000
EXPOSE 10000

ENTRYPOINT ["dotnet", "SmartCity.API.dll"]