FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY ["SmartCity.API/SmartCity.API.csproj", "SmartCity.API/"]
RUN dotnet restore "SmartCity.API/SmartCity.API.csproj"

COPY . .

WORKDIR "/src/SmartCity.API"

ARG SIXLABORS_LICENSE_KEY

RUN dotnet publish "SmartCity.API.csproj" \
    -c Release \
    -o /app/publish \
    /p:UseAppHost=false \
    /p:SixLaborsLicenseKey="$SIXLABORS_LICENSE_KEY"

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime

WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "SmartCity.API.dll"]